name: clack_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  svg_flutter: ^0.0.1
  flutter_slidable: ^3.0.0
  flutter_bloc: ^8.1.3
  url_launcher: ^6.2.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  photo_view: ^0.14.0
  socket_io_client: ^2.0.3+1
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  firebase_core: ^2.24.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  google_sign_in: ^6.1.6
  email_otp: ^2.1.1
  multiple_stream_builder: ^3.0.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/jpeg/
    - assets/images/png/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: poppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: poppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: poppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: poppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
